/usr/lib/jvm/java-7-openjdk-amd64/bin/javadoc \
-doclet com.parrot.docdown.DocdownDoclet \
-docletpath build/libs/docdown.jar \
-link http://docs.oracle.com/javase/7/docs/api/ \
-t "Docdown Doclet" \
-private \
-d build/docdown \
-sourcepath src/main/java \
-docsourcepath doc \
-includepath src/sample/java \
-subpackages com.parrot.docdown
